# Generated by Django 6.0.5 on 2026-07-20 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_cancel_reason_booking_cancelled_at_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='payment',
            name='held_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_logs', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='log_type',
            field=models.CharField(choices=[('payment_created', 'Pembayaran Dibuat'), ('payment_success', 'Pembayaran Berhasil'), ('payment_held', 'Dana Ditahan'), ('payment_released', 'Dana Dirilis'), ('payment_refunded', 'Pembayaran Dikembalikan'), ('payment_failed', 'Pembayaran Gagal'), ('booking_status_change', 'Status Booking Berubah'), ('security_alert', 'Peringatan Keamanan')], default='payment_created', max_length=30),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Pembayaran'), ('processing', 'Sedang Diproses'), ('success', 'Pembayaran Berhasil'), ('held', 'Dana Ditahan (Escrow)'), ('released', 'Dana Dirilis ke Healer'), ('failed', 'Gagal'), ('refunded', 'Dikembalikan'), ('expired', 'Kadaluarsa')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.payment'),
        ),
    ]
