# Generated by Django 6.0.5 on 2026-07-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_transactionlog_options_payment_held_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Pembayaran'), ('processing', 'Sedang Diproses'), ('success', 'Pembayaran Berhasil'), ('held', 'Dana Ditahan (Escrow)'), ('released', 'Dana Dirilis ke Healer'), ('failed', 'Gagal'), ('refunded', 'Dikembalikan'), ('expired', 'Kadaluarsa')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='log_type',
            field=models.CharField(choices=[('payment_created', 'Pembayaran Dibuat'), ('payment_success', 'Pembayaran Berhasil'), ('payment_held', 'Dana Ditahan'), ('payment_released', 'Dana Dirilis'), ('payment_refunded', 'Pembayaran Dikembalikan'), ('payment_failed', 'Pembayaran Gagal'), ('booking_status_change', 'Status Booking Berubah'), ('security_alert', 'Peringatan Keamanan')], db_index=True, default='payment_created', max_length=30),
        ),
    ]
