# Generated by Django 6.0.5 on 2026-07-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_seed_payment_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_code',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
    ]
