# Generated by Django 6.0.5 on 2026-08-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_seed_currencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='proof_image',
            field=models.ImageField(blank=True, help_text='Bukti pembayaran berupa screenshot/struk transfer', null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof_note',
            field=models.TextField(blank=True, verbose_name='Catatan bukti pembayaran'),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu unggah bukti'),
        ),
    ]
