# Generated by Django 6.0.5 on 2026-07-18 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healers', '0002_location_speciality_testimonial_healingcenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('reply', models.TextField(blank=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('healer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='healers.healer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealerPaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_name', models.CharField(blank=True, max_length=200)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('gopay_number', models.CharField(blank=True, max_length=20)),
                ('ovo_number', models.CharField(blank=True, max_length=20)),
                ('dana_number', models.CharField(blank=True, max_length=20)),
                ('paypal_email', models.EmailField(blank=True, max_length=254)),
                ('accept_cash', models.BooleanField(default=True)),
                ('accept_transfer', models.BooleanField(default=True)),
                ('accept_gopay', models.BooleanField(default=False)),
                ('accept_ovo', models.BooleanField(default=False)),
                ('accept_dana', models.BooleanField(default=False)),
                ('accept_paypal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('healer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_settings', to='healers.healer')),
            ],
        ),
        migrations.CreateModel(
            name='HealerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price_idr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('healer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='healers.healer')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
