# Generated by Django 6.0.5 on 2026-07-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healers', '0003_healermessage_healerpaymentsetting_healerservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='swift_code',
            field=models.CharField(blank=True, help_text='Kode SWIFT/BIC untuk transfer internasional', max_length=20),
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='visa_mc_enabled',
            field=models.BooleanField(default=False, help_text='Aktifkan pembayaran Visa/Mastercard via PayPal'),
        ),
    ]
