# Generated by Django 6.0.5 on 2026-07-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healers', '0005_chatroom_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='healer',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
