# Generated by Django 6.0.5 on 2026-07-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healers', '0006_alter_chatmessage_is_read_alter_healer_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='healingcenter',
            name='max_price_idr',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Harga maksimum dalam IDR', max_digits=12),
        ),
        migrations.AddField(
            model_name='healingcenter',
            name='min_price_idr',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Harga minimum dalam IDR', max_digits=12),
        ),
    ]
