# Generated by Django 6.0.5 on 2026-07-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healers', '0008_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healerpaymentsetting',
            options={'verbose_name_plural': 'Healer Payment Settings'},
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='accept_qris',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='accept_visa_mc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='auto_confirm',
            field=models.BooleanField(default=False, help_text='Konfirmasi otomatis setelah pembayaran berhasil'),
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='deposit_percent',
            field=models.PositiveIntegerField(default=50, help_text='Persentase deposit (1-100)'),
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='enable_escrow',
            field=models.BooleanField(default=True, help_text='Aktifkan escrow (dana ditahan hingga pekerjaan selesai)'),
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='enable_refund',
            field=models.BooleanField(default=True, help_text='Aktifkan pengembalian dana'),
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='min_payment_idr',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum pembayaran dalam IDR (0 = tanpa minimum)', max_digits=12),
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='payment_timeout_hours',
            field=models.PositiveIntegerField(default=24, help_text='Batas waktu pembayaran dalam jam'),
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='qris_id',
            field=models.CharField(blank=True, help_text='ID Merchant QRIS', max_length=50),
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='qris_merchant_name',
            field=models.CharField(blank=True, help_text='Nama merchant QRIS', max_length=200),
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='require_deposit',
            field=models.BooleanField(default=False, help_text='Wajibkan deposit sebelum booking'),
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='require_proof',
            field=models.BooleanField(default=False, help_text='Wajibkan bukti transfer dari customer'),
        ),
    ]
