# Generated by Django 6.0.5 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healers', '0009_alter_healerpaymentsetting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='accept_shopeepay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='accept_linkaja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='accept_isaku',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='shopeepay_number',
            field=models.CharField(blank=True, help_text='Nomor ShopeePay', max_length=20),
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='linkaja_number',
            field=models.CharField(blank=True, help_text='Nomor LinkAja', max_length=20),
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='isaku_number',
            field=models.CharField(blank=True, help_text='Nomor iSaku', max_length=20),
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='payment_gateway',
            field=models.CharField(blank=True, help_text='Payment gateway: midtrans, xendit, doku, tripay, manual', max_length=50),
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='pg_midtrans_server_key',
            field=models.CharField(blank=True, help_text='Midtrans Server Key', max_length=200),
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='pg_midtrans_client_key',
            field=models.CharField(blank=True, help_text='Midtrans Client Key', max_length=200),
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='pg_midtrans_merchant_id',
            field=models.CharField(blank=True, help_text='Midtrans Merchant ID', max_length=100),
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='pg_xendit_secret_key',
            field=models.CharField(blank=True, help_text='Xendit Secret Key', max_length=200),
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='pg_xendit_api_key',
            field=models.CharField(blank=True, help_text='Xendit API Key', max_length=200),
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='pg_doku_client_key',
            field=models.CharField(blank=True, help_text='DOKU Client Key', max_length=200),
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='pg_doku_merchant_id',
            field=models.CharField(blank=True, help_text='DOKU Merchant ID', max_length=100),
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='pg_tripay_api_key',
            field=models.CharField(blank=True, help_text='Tripay API Key', max_length=200),
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='pg_tripay_private_key',
            field=models.CharField(blank=True, help_text='Tripay Private Key', max_length=200),
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='pg_tripay_merchant_code',
            field=models.CharField(blank=True, help_text='Tripay Merchant Code', max_length=100),
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='va_bank_enabled',
            field=models.BooleanField(default=False, help_text='Aktifkan pembayaran Virtual Account'),
        ),
        migrations.AddField(
            model_name='healerpaymentsetting',
            name='va_banks',
            field=models.CharField(blank=True, help_text='Daftar bank VA: BCA,Mandiri,BRI,BNI,BSI, dll', max_length=500),
        ),
    ]
