# Generated by Django 6.0.5 on 2026-07-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healers', '0010_healerpaymentsetting_accept_shopeepay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransactionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(choices=[
                    ('BCA', 'Bank BCA'), ('Mandiri', 'Bank Mandiri'), ('BRI', 'Bank BRI'),
                    ('BNI', 'Bank BNI'), ('BTN', 'Bank BTN'), ('BSI', 'Bank BSI (Syariah)'),
                    ('BRIS', 'Bank BRI Syariah'), ('BNIS', 'Bank BNI Syariah'),
                    ('CIMB', 'CIMB Niaga'), ('Danamon', 'Bank Danamon'), ('Permata', 'Bank Permata'),
                    ('OCBC', 'OCBC NISP'), ('Maybank', 'Maybank'), ('Mega', 'Bank Mega'),
                    ('Panin', 'Bank Panin'), ('Bukopin', 'Bank Bukopin'), ('Sinarmas', 'Bank Sinarmas'),
                    ('Commonwealth', 'Bank Commonwealth'), ('Muamalat', 'Bank Muamalat'),
                    ('Jago', 'Bank Jago'), ('NeoCommerce', 'Bank Neo Commerce'),
                    ('Seabank', 'Sea Bank'), ('Digibank', 'Digibank (DBS)'),
                    ('BJP', 'BJB'), ('MandiriSyariah', 'Bank Mandiri Syariah'),
                ], max_length=50)),
                ('is_active', models.BooleanField(default=False, help_text='Aktifkan bank ini untuk transaksi')),
                ('account_number', models.CharField(blank=True, help_text='Nomor rekening / Virtual Account', max_length=50)),
                ('account_name', models.CharField(blank=True, help_text='Nama pemegang rekening', max_length=200)),
                ('branch', models.CharField(blank=True, help_text='Cabang bank', max_length=100)),
                ('accept_va', models.BooleanField(default=False, help_text='Terima pembayaran via Virtual Account')),
                ('accept_transfer', models.BooleanField(default=True, help_text='Terima transfer manual')),
                ('accept_qris', models.BooleanField(default=False, help_text='Terima QRIS via bank ini')),
                ('sop_va', models.TextField(blank=True, help_text='SOP instruksi Virtual Account')),
                ('sop_transfer', models.TextField(blank=True, help_text='SOP instruksi transfer manual')),
                ('sop_qris', models.TextField(blank=True, help_text='SOP instruksi QRIS')),
                ('va_code', models.CharField(blank=True, help_text='Kode prefix VA', max_length=50)),
                ('admin_fee', models.DecimalField(decimal_places=2, default=0, help_text='Biaya admin tambahan', max_digits=10)),
                ('min_transfer', models.DecimalField(decimal_places=2, default=0, help_text='Minimum transfer', max_digits=12)),
                ('max_transfer', models.DecimalField(decimal_places=2, default=0, help_text='Maximum transfer (0=tanpa batas)', max_digits=12)),
                ('payment_timeout_minutes', models.PositiveIntegerField(default=60, help_text='Batas waktu pembayaran dalam menit')),
                ('auto_cancel', models.BooleanField(default=True, help_text='Batalkan otomatis jika timeout')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('healer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transaction_settings', to='healers.healer')),
            ],
            options={
                'ordering': ['sort_order', 'bank_code'],
                'unique_together': {('healer', 'bank_code')},
            },
        ),
    ]
