# Generated by Django 6.0.5 on 2026-07-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healers', '0011_banktransactionsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransactionsetting',
            name='admin_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Biaya admin tambahan (0 = gratis)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='banktransactionsetting',
            name='max_transfer',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum transfer (0 = tanpa batas)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='banktransactionsetting',
            name='va_code',
            field=models.CharField(blank=True, help_text='Kode prefix VA (contoh: 1234 untuk BCA VA 1234xxxxxx)', max_length=50),
        ),
    ]
