# Generated by Django 6.0.5 on 2026-08-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healers', '0013_seed_reference_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='healer',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='healer_covers/'),
        ),
    ]
