# Generated by Django 6.0.5 on 2026-07-18 03:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('healers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(default=uuid.uuid4, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('service_type', models.CharField(max_length=200)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('total_price_idr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='IDR', max_length=10)),
                ('total_price_converted', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Konfirmasi'), ('confirmed', 'Dikonfirmasi'), ('in_progress', 'Sedang Berlangsung'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan'), ('expired', 'Kadaluarsa')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('healer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='healers.healer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('healer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='healers.healer')),
            ],
            options={
                'unique_together': {('healer', 'date', 'start_time')},
            },
        ),
    ]
