# Generated by Django 6.0.5 on 2026-07-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_cancel_reason_booking_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Menunggu Pembayaran'), ('pending_confirm', 'Menunggu Konfirmasi Healer'), ('confirmed', 'Dikonfirmasi'), ('in_progress', 'Sedang Dikerjakan'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan'), ('expired', 'Kadaluarsa'), ('refunded', 'Dikembalikan')], db_index=True, default='pending_payment', max_length=20),
        ),
    ]
